name: medical_qa_app
description: A simple Flutter frontend for the Medical QA FastAPI backend (PDF upload + ask).
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  file_picker: ^8.0.3
  http_parser: ^4.0.2
  url_launcher: ^6.3.0
  flutter_riverpod: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
